aluno/urls.py
from .routes import aluno, classe, matricula, ano, dashboard, report, telefone # Importando seus arquivos da pasta urls
from django.urls import path, include

urlpatterns = [
    path('aluno/', include(aluno.urlpatterns)),
    path('classe/', include(classe.urlpatterns)),
    path('matricula/', include(matricula.urlpatterns)),
    path('ano/', include(ano.urlpatterns)),
    path('dashboard/', include(dashboard.urlpatterns)),
    path('report/', include(report.urlspatterns)),
    path('telefone/', include(telefone.urlspatterns))


]

urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    

    path('', include('app_central.urls')),
    
    
    path("aluno/", include("aluno.urls")),
    
    
    path('rh/', include('rh.urls'))
    


    
]

aluno/models/__initi__.py
from .aluno import Aluno
from .ano import Ano
from .matricula import Matricula
from .classe import Classe

aluno/models/classe.py
from django.db import models

from aluno.models.ano import Ano


# Create your models here.
#Classe do ano (NÃO IMPLEMENTADO)
class Classe(models.Model):
    
    class Meta:
        unique_together =(("serie", "turma", "ano"))
        
    PERIODO_CHOICES = (
        ("M","MANHÃ"),
        ("T","TARDE"),
        ("I","INTEGRAL")
    )
    serie = models.CharField(max_length=1, blank=False, null=False )
    turma = models.CharField(max_length=1, blank=False, null=False)
    ano = models.ForeignKey(Ano, on_delete=models.RESTRICT, blank=False, null=False)
    periodo = models.CharField(max_length=1, choices=PERIODO_CHOICES, blank=False, null=False)
    
    def __str__(self):
        periodo = self.retornarDescricaoPeriodo()
        return f'{self.serie}º {self.turma} {periodo}'
    
    def retornarPeriodos():
        return Classe.PERIODO_CHOICES
    
    #Verificar matrículas na sala e retornar o próximo elmento
    def retornarProximoNumeroClasse(tipo_objeto, campo_pesquisa):
        elementos = tipo_objeto.objects.filter(classe=campo_pesquisa)
        numero = len(elementos) + 1
        return numero
    
    def retornarDescricaoPeriodo(self):
        for i in range(len(self.PERIODO_CHOICES)):
            if self.periodo == self.PERIODO_CHOICES[i][0]:
                return self.PERIODO_CHOICES[i][1]
    
    class Meta:
        app_label = 'aluno'

aluno/forms/aluno.py
from django import forms
from aluno.models.aluno import Aluno
from aluno.utils.texto import padronizar_nome

class FrmAluno(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = ['nome', 'ra']
        widgets = {
            'nome': forms.TextInput(attrs={
                'class': 'form-control formulario',
                'placeholder': 'Nome do Aluno',
                'aria-describedby': 'basic-addon1'
            }),
            'ra': forms.NumberInput(attrs={
                'class': 'form-control formulario',
                'placeholder': 'RA'
            }),
        }
        
    def clean_nome(self):
        nome = self.cleaned_data.get('nome')
        return padronizar_nome(nome)

class FrmAlunoUpdate(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = [
            'nome',
            'ra',
            'd_ra',
            'data_nascimento',
        ]
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'ra': forms.NumberInput(attrs={'class': 'form-control'}),
            'd_ra': forms.TextInput(attrs={
                'class': 'form-control',
                'maxlength': 1
            }),
            'data_nascimento': forms.DateInput(
                format='%Y-%m-%d',
                attrs={
                    'type': 'date',
                    'class': 'form-control'
                }
            ),
        }

    def clean_nome(self):
        nome = self.cleaned_data.get('nome')
        return padronizar_nome(nome)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['data_nascimento'].input_formats = ['%Y-%m-%d']


        
        

    

aluno/forms/classe.py
from django import forms
from aluno.models.classe import Classe

class FrmClasse(forms.ModelForm):
    class Meta:
        model = Classe
        fields = ['serie', 'turma', 'periodo']
        widgets = {
            'serie': forms.NumberInput(attrs={
                'class': 'form-control formulario',
                'placeholder': 'Série'
            }),
            'turma': forms.TextInput(attrs={
                'class': 'form-control formulario',
                'placeholder': 'Turma'
            }),
            'periodo': forms.Select(attrs={
                'class': 'form-control formulario'
            }),
        }
        
class FrmClasseUpdate(forms.ModelForm):
    class Meta:
        model = Classe
        fields = ['serie', 'turma', 'periodo']
        widgets = {
            'serie': forms.NumberInput(attrs={
                'class': 'form-control formulario',
                'placeholder': 'Série'
            }),
            'turma': forms.TextInput(attrs={
                'class': 'form-control formulario',
                'placeholder': 'Turma'
            }),
            'periodo': forms.Select(attrs={
                'class': 'form-control formulario'
            }),
        }

aluno/routes/aluno.py
from django.urls import path


from aluno.views.aluno import (atualizar_aluno,
                    pesquisar_aluno,
                    buscar_dados_aluno,
                    buscarRMCancelar, cancelarRM, salvar_aluno,
                    index, recarregarTabela)

urlpatterns = [
    path("", index, name="inicial"),  
    path("salvar", salvar_aluno, name="salvar_aluno"),
    path("buscarDadosAluno", buscar_dados_aluno, name="buscarDadosAluno"), 
    path("atualizar", atualizar_aluno, name="atualizar"),
    path("pesquisar", pesquisar_aluno, name="pesquisar_aluno"),
    path("buscarRMCancelar", buscarRMCancelar, name="buscarRMCancelar"), 
    path("recarregarTabela", recarregarTabela, name="recarregarTabela"),
    path("cancelarRM", cancelarRM, name="cancelarRM"), 
        
    
]

aluno/routes/ano.py
from django.urls import path

from aluno.views.ano import (buscar_ano, excluir_ano, fechar_abrir_ano, gravar_ano,
                    inicial_ano, listar_ano, selecionar_ano, status_ano)

urlpatterns = [
    path("gravarano", gravar_ano, name="gravar_ano"),  
    path("fecharabrirano", fechar_abrir_ano, name="fechar_abrir_ano"),
    path("statusano", status_ano, name="status_ano"),
    path("", inicial_ano, name="ano"),
    path("listarano", listar_ano, name="listar_ano"),
    path("buscarano", buscar_ano, name="buscar_ano"),
    path("excluirano", excluir_ano, name="excluir_ano"),
    path("selecionarano", selecionar_ano, name="selecionar_ano")

]

aluno/routes/classe.py
from django.urls import path

from aluno.views.classe import (atualizar, buscar_classe, classe, deletar, exibirClasse,
                    exibirQuadro, gerarTurmas, gravar, listar_classe,
                    carregar_classes)

urlpatterns = [
    path('', classe, name='classe'),
    path('gravarclasse', gravar, name='gravar_classe'),
    path('atualizarclasse', atualizar, name='atualizar_classe'),
    path('deletarclasse', deletar, name='deletar_classe'),
    path('listarclasse', listar_classe, name='listar_classe'),
    path('buscarclasse', buscar_classe, name='buscar_classe'),
    path('exibirQuadro', exibirQuadro, name='exibir_quadro'),
    path('gerarTurmas', gerarTurmas, name='gerar_turmas'),
    path('exibirClasse', exibirClasse, name='exibir_classe'),
    path("carregarClasses", carregar_classes, name="carregarclasses"),

    
]

aluno/routes/dashboard.py
from django.urls import path

from aluno.views.dashboard import dashboard, visualizar_alunos_mes, visualizar_alunos_periodo

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('visperiodo', visualizar_alunos_periodo, name='visperiodo'),
    path('visqtdalunos', visualizar_alunos_mes, name='visqtdalunos')

]

aluno/routes/matricula.py
from django.urls import path

from aluno.views.matricula import (adicionarNaClasse, buscar_matricula,
                    buscarAluno, carregar_classes_remanejamento,
                    carregar_matriculas, carregar_movimentacao,
                    excluir_matricula, exibirTelaMatricula, matricula,
                    matricular_aluno_ia, movimentar, ordenar_em_alfabetica,
                    upload_matriculas, buscar_historico_matricula)
urlpatterns = [
    path('', matricula, name='matricula'),
    path('ordenarAlfabeto', ordenar_em_alfabetica, name='ordemalfabetica'),
    path('carregarClassesRemanejamento', carregar_classes_remanejamento, name='carregarclassesremanejamento'),
    path('carregarMovimentacao', carregar_movimentacao, name='carregarmovimentacao'),
    path('carregarMatriculas', carregar_matriculas, name='carregarmatriculas'),
    path('buscarMatricula', buscar_matricula, name='buscarmatricula'), 
    path('excluirMatricula', excluir_matricula, name='excluirmatricula'),
    path('movimentar', movimentar, name='movimentar'),
    path('importarMatriculas', upload_matriculas, name='uploadmatriculas'),
    path('buscarAluno', buscarAluno, name='buscaraluno'),
    path('adicionarNaClasse', adicionarNaClasse, name='adicionarnaclasse'),
    path('telamatricular', exibirTelaMatricula, name='telamatricular'),
    path('matricular_aluno_ia', matricular_aluno_ia, name='matricular_aluno_ia'),
    path("buscar_historico_matricula",buscar_historico_matricula, name="buscar_historico_matricula"),

]

aluno/routes/report.py
from django.urls import path
from aluno.views.report import (baixar_declaracao_matricula, 
                               baixar_lista_telefonica, baixar_pdf,
                               baixar_lista_alunos_personalizada)

urlspatterns = [
    path("baixardeclaracao", baixar_declaracao_matricula, name="baixar_declaracao_matricula"),
    path("baixarpdf", baixar_pdf, name="baixarpdf"),
    path("listatelefonicapdf", baixar_lista_telefonica, name='listatelefonicapdf'),
    path("listapersonalizada", baixar_lista_alunos_personalizada, name="alunos_personalizada")
]

aluno/routes/telefone.py
from django.urls import path
from aluno.views.telefone import bloco_contato, del_telefone

urlspatterns = [
    path("bloco_contato", bloco_contato, name="bloco_contato"),
    path("delTelefone", del_telefone, name="delTelefone"),
   
]

aluno/views/aluno.py
from django.shortcuts import render
from aluno.utils.texto import  padronizar_nome

from aluno.forms.aluno import FrmAluno, FrmAlunoUpdate
from aluno.models.aluno import Aluno
from django.shortcuts import get_object_or_404

from django.template.loader import render_to_string
from django.http import JsonResponse
from aluno.forms.telefone import TelefoneFormSet

from django.db import transaction


REF_TAMANHO_NOME = 2
REF_TAMANHO_RA = 7
EMAIL = "victorianonino@educa.orlandia.sp.gov.br"
from aluno.services.aluno import buscar_duplicados, renderizarTabela, pesquisar_alunos_por_nome
from aluno.services.mensagem import criarMensagemJson


def index(request):
    if request.method == "POST":
        # Se o formulário de cadastro de aluno foi enviado
        return salvar_aluno(request)
    # Se for GET, apenas renderiza o formulário
    form = FrmAluno()
    return render(request, "aluno/aluno/index.html", {"form": form})

# Gravar registro do Aluno
def salvar_aluno(request):
    nome = padronizar_nome(request.POST.get("nome"))
    ra = request.POST.get("ra")

    form = FrmAluno({"nome": nome, "ra": ra})

    # Validação RA duplicado
    if Aluno.objects.filter(ra=ra).exists():
        return JsonResponse({
            'success': False,
            'mensagem': criarMensagemJson(f'Já existe RA {ra} cadastrado para outro aluno!','danger')
        })

    if not form.is_valid():
        return JsonResponse({
            'success': False,
            'mensagem': criarMensagemJson(f'Dados Inválidos!','danger')
        })

    if len(nome) <= REF_TAMANHO_NOME:
        return JsonResponse({
            'success': False,
            'mensagem': criarMensagemJson(f'Nome muito Pequeno!','warning')
        })

    if len(ra) <= REF_TAMANHO_RA:
        return JsonResponse({
            'success': False,
            'mensagem': criarMensagemJson(f'RA muito Pequeno!','warning')
        })

    # Salva aluno
    form.save()

    alunos = Aluno.retornarNUltimos()
    nomes_duplicados = buscar_duplicados(alunos)
    html = renderizarTabela(alunos, nomes_duplicados, request)

    return JsonResponse({
        'success': True,
        'mensagem': criarMensagemJson(f'Aluno Registrado com Sucesso!','success'),
        'html': html
    })


@transaction.atomic
def atualizar_aluno(request):
    aluno = get_object_or_404(Aluno, rm=request.POST.get("rm"))

    form = FrmAlunoUpdate(request.POST, instance=aluno)
    formset = TelefoneFormSet(request.POST, instance=aluno)

    if form.is_valid() and formset.is_valid():
        form.save()
        formset.save()

        return JsonResponse({
            'success': True,
            'mensagem': criarMensagemJson(
                'Aluno atualizado com sucesso!!!',
                'success'
            )
        })

    return JsonResponse({
        'success': False,
        'html': render_to_string(
            'aluno/aluno/partials/form_update.html',
            {
                'form': form,
                'formset': formset,
                'aluno': aluno
            },
            request=request
        )
    })
        
def pesquisar_aluno(request):
    nome = padronizar_nome(request.POST.get("nome", ""))
    filtro = request.POST.get("filtro")

    if len(nome) <= REF_TAMANHO_NOME:
        # Últimos 5 registros
        alunos = Aluno.retornarNUltimos().prefetch_related('telefones')
        nomes_duplicados = buscar_duplicados(alunos)
        html = renderizarTabela(alunos, nomes_duplicados, request)
        return JsonResponse({'html': html, 'mensagem': ''})  # sem mensagem

    alunos = pesquisar_alunos_por_nome(nome, filtro).prefetch_related('telefones')
    nomes_duplicados = buscar_duplicados(alunos)
    html = renderizarTabela(alunos, nomes_duplicados, request)

    if not alunos:
       
        return JsonResponse({'html': '', 'mensagem': criarMensagemJson('Aluno não Encontrado!','info')})
    
    return JsonResponse({'html': html, 'mensagem': ''})
        
def cancelarRM(request):
    rm = request.POST.get("rm")
    try:
        aluno = Aluno.objects.get(rm=rm)
    except Aluno.DoesNotExist:
        return JsonResponse({"success": False, "mensagem":criarMensagemJson('Aluno não Encontrado!', 'info')})

    # Defina explicitamente o status de cancelado
    aluno.status = Aluno.STATUS_CANCELADO
    aluno.save()

    return JsonResponse({"success": False, "mensagem":criarMensagemJson(f'Aluno {aluno.nome}, RM {aluno.rm} Cancelado com Sucesso!', 'success')})
 
def recarregarTabela(request):
    alunos = Aluno.retornarNUltimos().prefetch_related('telefones')
    nomes_duplicados = buscar_duplicados(alunos)
    html = renderizarTabela(alunos, nomes_duplicados, request)
  
    return JsonResponse({'html': html, 'mensagem': ''})  # sem mensagem

def buscar_dados_aluno(request):
    aluno = get_object_or_404(Aluno, rm=request.POST.get("rm"))

    form = FrmAlunoUpdate(instance=aluno)
    formset = TelefoneFormSet(instance=aluno)

    return render(
        request,
        "aluno/aluno/partials/form_update.html",
        {
            "form": form,
            "formset": formset,
            "aluno": aluno,
        }
    )

def buscarRMCancelar(request):
    rm = request.POST.get('rm')
    aluno = Aluno.objects.values('rm', 'nome').get(pk=rm)
    return JsonResponse({"rm": aluno['rm'], "nome": aluno['nome']})

   

aluno/views/ano.py
from django.shortcuts import HttpResponse, render

from aluno.utils.mensagem_http import criarMensagem

from aluno.models.ano import Ano
from aluno.services.ano import efetuar_lancamentos_fechamento_ano

# Create your views here.
def inicial_ano(request):
    return render(request,"aluno/ano/ano.html")

def gravar_ano(request):
    ano = Ano(ano=request.GET.get('ano'))
    try:
        ano.save()
        return criarMensagem("Ano salvo com sucesso","success")
    except Exception as err:
        return criarMensagem(f"Erro ao salvar ano ({err})!", "danger")

def excluir_ano(request):
    ano = Ano.objects.filter(pk=request.GET.get('ano'))[0]
    try:
        ano.delete()
        return criarMensagem("Ano deletado com sucesso", "success")
    except:
        return criarMensagem(f"Erro ao excluir ano ({ano})!","danger")

def buscar_ano(request):
    try:
        ano_recebido = request.GET.get("ano")
        if ano_recebido == "":
            ano_recebido = 0
        ano = Ano.objects.filter(ano=ano_recebido).filter()
        if ano:
             return render(request, 'aluno/ano/partials/listar_anos.html', {
                    'anos': ano,
             })
        else:
            return criarMensagem("Nenhum resultado!","info")

    except Exception as err:
        print(err)
        return criarMensagem("Algum erro aconteceu!","danger")
    
def listar_ano(request):
    anos = Ano.objects.all().order_by('-ano')[:10]
    return render(request, 'aluno/ano/partials/listar_anos.html', {
        'anos': anos,
    })

def fechar_abrir_ano(request):
    ano = Ano.objects.get(pk=request.GET.get('ano'))
    ano.fechado = not ano.fechado
    ano.save()
    efetuar_lancamentos_fechamento_ano(ano)

    return HttpResponse(ano.fechado)
    
def status_ano(request):
    ano = Ano.objects.get(pk=request.GET.get('ano'))
    return HttpResponse(ano.fechado)

def selecionar_ano(request):
    ano = Ano.objects.filter(ano=request.GET.get('ano')).first()
    return HttpResponse(ano.id)
   

aluno/templates/aluno/classe/partials/form_update.html
<form id="atualizarClasse" method="POST">
    {% csrf_token %}
    <input type="hidden" name="classe_id" id="codClasse" value="{{ classe.id }}">
    <div class='row'>
        <div class='col form-group'>
            <label for='serie'>Série</label>
            {{form.serie}}
        </div>
        <div class='col form-group'>
            <label for='turma'>Turma</label>
            {{form.turma}}
        </div>
        <div class='col form-group'>
            <label for='periodo'>Período</label>
            {{form.periodo}}
        </div>
    </div>
</form>

aluno/templates/aluno/classe/partials/modal_atualizar.html
<div class="modal fade" id="atualizarModal" tabindex="-1" aria-labelledby="atualizarModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="atualizarModalLabel">
          Deseja alterar essa classe?
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="dadosClasse" class="row">
          <!-- Dados do Registro Aqui -->
        </div>
      </div>
      <div class="modal-footer mt-2">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">
          Cancelar
        </button>
        <button id="simAtualizar" type="button" class="btn btn-primary" data-bs-dismiss="modal">
          Atualizar
        </button>
        <button id="simDeletar" type="button" class="btn btn-warning" data-bs-dismiss="modal">
          Deletar
        </button>
      </div>
    </div>
  </div>
</div>

aluno/templates/aluno/classe/partials/modal_exibir_classe.html
<div class="row mt-3">
    <div class="col-12">
        <h5 class='bg-body-secondary d-flex rounded-5 justify-content-center p-2'><strong id="serie">{{ serie }}</strong>
            º <strong id="turma">{{ turma }}</strong> - <strong id="periodo">{{ periodo }}</strong>
        </h5>
        <table id="tabelaAlunos" class="table table-hover table-responsive">
            <thead>
                <th>Nº</th>
                <th>Nome do Aluno</th>
            </thead>
            <tbody>
                {% for matricula in matriculas %}
                <tr>
                    <td>{{ matricula.numero }}</td>
                    <td>{{ matricula.aluno__nome }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

aluno/templates/aluno/classe/partials/modal_quadro.html
<div class="modal fade" id="criarQuadroClasseModal" tabindex="-1" aria-labelledby="visualizarModalLabel"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="criarQuadroModalLabel">
          Criação do Quadro de Classes
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <div id="quadroClasse">
          <!-- Quadro aqui-->
        </div>
      </div>
      <div class="modal-footer mt-2">
        <button id="gerarTurmas" type="button" class="btn btn-warning" data-bs-dismiss="modal">
          Gerar Turmas
        </button>
      </div>
    </div>
  </div>
</div>

aluno/templates/aluno/classe/partials/modal_visualizar.html
<div class="modal fade" id="visualizarClasseModal" tabindex="-1" aria-labelledby="visualizarModalLabel"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="visualizarModalLabel">
          Visualização da Classe
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="alunosClasse">
        </div>
      </div>
      <div class="modal-footer mt-2"></div>
    </div>
  </div>
</div>

aluno/templates/aluno/classe/partials/quadro.html
<div class="row">
  <div class="col-3 text-center"><strong>Ano</strong></div>
  <div class="col-3 text-center"><strong>Manhã</strong></div>
  <div class="col-3 text-center"><strong>Tarde</strong></div>
  <div class="col-3 text-center"><strong>Integral</strong></div>
</div>

{% for linha in linhas %}
  <div class="row mt-2 d-flex justify-content-center align-items-center">
    <div class="col-3 text-center bg-body-secondary p-1 rounded-4">
      <strong>{{ linha.serie }}<span>º</span></strong>
    </div>

    <div class="col-3 text-center">
      <input type="number"
             class="form-control text-center"
             id="m{{ linha.serie }}"
             value="{{ linha.manha }}"
             {% if desabilita %}disabled{% endif %}>
    </div>

    <div class="col-3 text-center">
      <input type="number"
             class="form-control text-center"
             id="t{{ linha.serie }}"
             value="{{ linha.tarde }}"
             {% if desabilita %}disabled{% endif %}>
    </div>

    <div class="col-3 text-center">
      <input type="number"
             class="form-control text-center"
             id="i{{ linha.serie }}"
             value="{{ linha.integral }}"
             {% if desabilita %}disabled{% endif %}>
    </div>
  </div>
{% endfor %}

aluno/templates/aluno/classe/partials/tabela_classes.html
{# ========================= #}
{# ABAS POR SÉRIE            #}
{# ========================= #}

<ul class="nav nav-tabs" role="tablist">

  {% for serie, classes in classes_por_serie.items %}
    <li class="nav-item" role="presentation">
      <button
        class="nav-link {% if forloop.first %}active{% endif %}"
        data-bs-toggle="tab"
        data-bs-target="#serie-{{ serie }}"
        type="button"
        role="tab">

        {{ serie }}º Ano

        <span class="badge bg-dark ms-2">
          {{ classes|length }}
        </span>

      </button>
    </li>
  {% endfor %}

</ul>

{# ========================= #}
{# CONTEÚDO DAS ABAS         #}
{# ========================= #}

<div class="tab-content mt-3">

  {% for serie, classes in classes_por_serie.items %}
    <div
      class="tab-pane fade {% if forloop.first %}show active{% endif %}"
      id="serie-{{ serie }}"
      role="tabpanel">

      <table class="table table-hover table-bordered table-success m-2">

        <thead class="text-center">
          <tr>
            <th>Série</th>
            <th>Turma</th>
            <th>Período</th>
            <th>Atualizar</th>
            <th>Visualizar</th>
          </tr>
        </thead>

        <tbody class="corpoTabelaTurmas">

          {% for c in classes %}
            <tr>
              <td class="text-center">{{ c.serie }}</td>
              <td class="text-center">{{ c.turma }}</td>
              <td class="text-center">{{ c.get_periodo_display }}</td>

              <td class="text-center">
                <button
                  type="button"
                  class="btn btn-outline-dark btn-lg atualizar"
                  data-id="{{ c.id }}"
                  data-bs-toggle="modal"
                  data-bs-target="#atualizarModal">
                  <i class="bi bi-arrow-repeat"></i>
                </button>
              </td>

              <td class="text-center">
                <button
                  type="button"
                  class="btn btn-outline-dark btn-lg visualizar"
                  data-id="{{ c.id }}"
                  data-bs-toggle="modal"
                  data-bs-target="#visualizarClasseModal">
                  <i class="bi bi-eye"></i>
                </button>
              </td>
            </tr>

          {% empty %}
            <tr>
              <td colspan="5" class="text-center text-muted">
                Nenhuma classe cadastrada
              </td>
            </tr>
          {% endfor %}

        </tbody>
      </table>

    </div>
  {% endfor %}

</div>