aluno/urls.py
from .routes import aluno, classe, matricula, ano, dashboard, report, telefone # Importando seus arquivos da pasta urls
from django.urls import path, include

urlpatterns = [
    path('aluno/', include(aluno.urlpatterns)),
    path('classe/', include(classe.urlpatterns)),
    path('matricula/', include(matricula.urlpatterns)),
    path('ano/', include(ano.urlpatterns)),
    path('dashboard/', include(dashboard.urlpatterns)),
    path('report/', include(report.urlspatterns)),
    path('telefone/', include(telefone.urlspatterns))


]

urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    

    path('', include('app_central.urls')),
    
    
    path("aluno/", include("aluno.urls")),
    
    
    path('rh/', include('rh.urls'))
    


    
]

aluno/models/__initi__.py
from .aluno import Aluno
from .ano import Ano
from .matricula import Matricula
from .classe import Classe

aluno/models/aluno.py
from django.db import models


# Create your models here.
# Aluno
class Aluno (models.Model):
    
    STATUS_ARQUIVADO = 0
    STATUS_CANCELADO = 1
    STATUS_ATIVO = 2

    STATUS_CHOICES = (
        (STATUS_ARQUIVADO, "Arquivado"),
        (STATUS_CANCELADO, "Cancelado"),
        (STATUS_ATIVO, "Ativo"),
    )
    
    rm = models.IntegerField(primary_key=True,)
    nome = models.CharField(max_length=150)
    #status (0 - arquivado, 1 - cancelado, 2 - ativo) 
    status = models.IntegerField(choices=STATUS_CHOICES, default=STATUS_ARQUIVADO)
    ra = models.CharField(max_length=100, default='')
    d_ra = models.CharField(max_length=1, default='', null=True, blank=True)
    data_nascimento = models.DateField(null=True, blank=True)
 
    def __str__(self):
        return f'{self.nome}'
    
    @property
    def is_ativo(self):
        return self.status == self.STATUS_ATIVO

    @property
    def is_cancelado(self):
        return self.status == self.STATUS_CANCELADO

    @property
    def is_arquivado(self):
        return self.status == self.STATUS_ARQUIVADO    
    
    @classmethod
    def retornarNUltimos(cls, n=6):
        alunos = cls.objects.order_by('-rm')[:n]
        return alunos
    
    def matricula_ativa(self):
        return self.matriculas.filter(situacao="C").select_related('classe').first()
    
    class Meta:
        app_label = 'aluno'
    

#Documentos do aluno (NÃO IMPLEMENTADO)
class Prontuario(models.Model):
    DOCUMENTO_CHOICES = (
        ('CN','Certidão de Nascimento'),
        ('RGA','RG - Aluno'),
        ('CPFA','CPF - Aluno'),
        ('CV','Carteira Vacinação'),
        ('RGR','RG - Responsável'),
        ('CPFR','CPF - Responsável'),
        ('CNH','CNH'),
        ('FM','Ficha de Matrícula'),
        ('CR','Comprovante de Residência'),
        ('LD','Laudo'),
        ('OT','Outros')
    )
    #aluno = models.ForeignKey(Aluno)
    descricao = models.CharField(max_length=4, choices=DOCUMENTO_CHOICES, blank=False, null=False, default='') 
    caminho = models.ImageField()
    
    class Meta:
        app_label = 'aluno'

    
    

    

aluno/forms/aluno.py
from django import forms
from aluno.models.aluno import Aluno
from aluno.utils.texto import padronizar_nome

class FrmAluno(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = ['nome', 'ra']
        widgets = {
            'nome': forms.TextInput(attrs={
                'class': 'form-control formulario',
                'placeholder': 'Nome do Aluno',
                'aria-describedby': 'basic-addon1'
            }),
            'ra': forms.NumberInput(attrs={
                'class': 'form-control formulario',
                'placeholder': 'RA'
            }),
        }
        
    def clean_nome(self):
        nome = self.cleaned_data.get('nome')
        return padronizar_nome(nome)

class FrmAlunoUpdate(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = [
            'nome',
            'ra',
            'd_ra',
            'data_nascimento',
        ]
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'ra': forms.NumberInput(attrs={'class': 'form-control'}),
            'd_ra': forms.TextInput(attrs={
                'class': 'form-control',
                'maxlength': 1
            }),
            'data_nascimento': forms.DateInput(
                format='%Y-%m-%d',
                attrs={
                    'type': 'date',
                    'class': 'form-control'
                }
            ),
        }

    def clean_nome(self):
        nome = self.cleaned_data.get('nome')
        return padronizar_nome(nome)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['data_nascimento'].input_formats = ['%Y-%m-%d']


        
        

    

aluno/forms/matricula.py
from django import forms
# importação de afastamentos
class ImportarMatriculasForm(forms.Form):
    arquivo = forms.FileField(
        label="Relatório de Matrícula da Classe (PDF)",
        widget=forms.ClearableFileInput(
            attrs={"class": "form-control",
                   "accept": "application/pdf"}
            )                          
    )

aluno/routes/aluno.py
from django.urls import path


from aluno.views.aluno import (atualizar_aluno,
                    pesquisar_aluno,
                    buscar_dados_aluno,
                    buscarRMCancelar, cancelarRM, salvar_aluno,
                    index, recarregarTabela)

urlpatterns = [
    path("", index, name="inicial"),  
    path("salvar", salvar_aluno, name="salvar_aluno"),
    path("buscarDadosAluno", buscar_dados_aluno, name="buscarDadosAluno"), 
    path("atualizar", atualizar_aluno, name="atualizar"),
    path("pesquisar", pesquisar_aluno, name="pesquisar_aluno"),
    path("buscarRMCancelar", buscarRMCancelar, name="buscarRMCancelar"), 
    path("recarregarTabela", recarregarTabela, name="recarregarTabela"),
    path("cancelarRM", cancelarRM, name="cancelarRM"), 
        
    
]

aluno/routes/ano.py
from django.urls import path

from aluno.views.ano import (buscar_ano, excluir_ano, fechar_abrir_ano, gravar_ano,
                    inicial_ano, listar_ano, selecionar_ano, status_ano)

urlpatterns = [
    path("gravarano", gravar_ano, name="gravar_ano"),  
    path("fecharabrirano", fechar_abrir_ano, name="fechar_abrir_ano"),
    path("statusano", status_ano, name="status_ano"),
    path("", inicial_ano, name="ano"),
    path("listarano", listar_ano, name="listar_ano"),
    path("buscarano", buscar_ano, name="buscar_ano"),
    path("excluirano", excluir_ano, name="excluir_ano"),
    path("selecionarano", selecionar_ano, name="selecionar_ano")

]

aluno/routes/classe.py
from django.urls import path

from aluno.views.classe import (atualizar, buscar_classe, classe, deletar, exibirClasse,
                    exibirQuadro, gerarTurmas, gravar, listar_classe,
                    carregar_classes)

urlpatterns = [
    path('', classe, name='classe'),
    path('gravarclasse', gravar, name='gravar_classe'),
    path('atualizarclasse', atualizar, name='atualizar_classe'),
    path('deletarclasse', deletar, name='deletar_classe'),
    path('listarclasse', listar_classe, name='listar_classe'),
    path('buscarclasse', buscar_classe, name='buscar_classe'),
    path('exibirQuadro', exibirQuadro, name='exibir_quadro'),
    path('gerarTurmas', gerarTurmas, name='gerar_turmas'),
    path('exibirClasse', exibirClasse, name='exibir_classe'),
    path("carregarClasses", carregar_classes, name="carregarclasses"),

    
]

aluno/routes/dashboard.py
from django.urls import path

from aluno.views.dashboard import dashboard, visualizar_alunos_mes, visualizar_alunos_periodo

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('visperiodo', visualizar_alunos_periodo, name='visperiodo'),
    path('visqtdalunos', visualizar_alunos_mes, name='visqtdalunos')

]

aluno/routes/matricula.py
from django.urls import path

from aluno.views.matricula import (adicionarNaClasse, buscar_matricula,
                    buscarAluno, carregar_classes_remanejamento,
                    carregar_matriculas, carregar_movimentacao,
                    excluir_matricula, exibirTelaMatricula, matricula,
                    matricular_aluno_ia, movimentar, ordenar_em_alfabetica,
                    upload_matriculas, buscar_historico_matricula)
urlpatterns = [
    path('', matricula, name='matricula'),
    path('ordenarAlfabeto', ordenar_em_alfabetica, name='ordemalfabetica'),
    path('carregarClassesRemanejamento', carregar_classes_remanejamento, name='carregarclassesremanejamento'),
    path('carregarMovimentacao', carregar_movimentacao, name='carregarmovimentacao'),
    path('carregarMatriculas', carregar_matriculas, name='carregarmatriculas'),
    path('buscarMatricula', buscar_matricula, name='buscarmatricula'), 
    path('excluirMatricula', excluir_matricula, name='excluirmatricula'),
    path('movimentar', movimentar, name='movimentar'),
    path('importarMatriculas', upload_matriculas, name='uploadmatriculas'),
    path('buscarAluno', buscarAluno, name='buscaraluno'),
    path('adicionarNaClasse', adicionarNaClasse, name='adicionarnaclasse'),
    path('telamatricular', exibirTelaMatricula, name='telamatricular'),
    path('matricular_aluno_ia', matricular_aluno_ia, name='matricular_aluno_ia'),
    path("buscar_historico_matricula",buscar_historico_matricula, name="buscar_historico_matricula"),

]

aluno/routes/report.py
from django.urls import path
from aluno.views.report import (baixar_declaracao_matricula, 
                               baixar_lista_telefonica, baixar_pdf,
                               baixar_lista_alunos_personalizada)

urlspatterns = [
    path("baixardeclaracao", baixar_declaracao_matricula, name="baixar_declaracao_matricula"),
    path("baixarpdf", baixar_pdf, name="baixarpdf"),
    path("listatelefonicapdf", baixar_lista_telefonica, name='listatelefonicapdf'),
    path("listapersonalizada", baixar_lista_alunos_personalizada, name="alunos_personalizada")
]

aluno/routes/telefone.py
from django.urls import path
from aluno.views.telefone import bloco_contato, del_telefone

urlspatterns = [
    path("bloco_contato", bloco_contato, name="bloco_contato"),
    path("delTelefone", del_telefone, name="delTelefone"),
   
]

aluno/views/aluno.py
from django.shortcuts import render
from aluno.utils.texto import  padronizar_nome

from aluno.forms.aluno import FrmAluno, FrmAlunoUpdate
from aluno.models.aluno import Aluno
from django.shortcuts import get_object_or_404

from django.template.loader import render_to_string
from django.http import JsonResponse
from aluno.forms.telefone import TelefoneFormSet

from django.db import transaction


REF_TAMANHO_NOME = 2
REF_TAMANHO_RA = 7
EMAIL = "victorianonino@educa.orlandia.sp.gov.br"
from aluno.services.aluno import buscar_duplicados, renderizarTabela, pesquisar_alunos_por_nome
from aluno.services.mensagem import criarMensagemJson


def index(request):
    if request.method == "POST":
        # Se o formulário de cadastro de aluno foi enviado
        return salvar_aluno(request)
    # Se for GET, apenas renderiza o formulário
    form = FrmAluno()
    return render(request, "aluno/aluno/index.html", {"form": form})

# Gravar registro do Aluno
def salvar_aluno(request):
    nome = padronizar_nome(request.POST.get("nome"))
    ra = request.POST.get("ra")

    form = FrmAluno({"nome": nome, "ra": ra})

    # Validação RA duplicado
    if Aluno.objects.filter(ra=ra).exists():
        return JsonResponse({
            'success': False,
            'mensagem': criarMensagemJson(f'Já existe RA {ra} cadastrado para outro aluno!','danger')
        })

    if not form.is_valid():
        return JsonResponse({
            'success': False,
            'mensagem': criarMensagemJson(f'Dados Inválidos!','danger')
        })

    if len(nome) <= REF_TAMANHO_NOME:
        return JsonResponse({
            'success': False,
            'mensagem': criarMensagemJson(f'Nome muito Pequeno!','warning')
        })

    if len(ra) <= REF_TAMANHO_RA:
        return JsonResponse({
            'success': False,
            'mensagem': criarMensagemJson(f'RA muito Pequeno!','warning')
        })

    # Salva aluno
    form.save()

    alunos = Aluno.retornarNUltimos()
    nomes_duplicados = buscar_duplicados(alunos)
    html = renderizarTabela(alunos, nomes_duplicados, request)

    return JsonResponse({
        'success': True,
        'mensagem': criarMensagemJson(f'Aluno Registrado com Sucesso!','success'),
        'html': html
    })


@transaction.atomic
def atualizar_aluno(request):
    aluno = get_object_or_404(Aluno, rm=request.POST.get("rm"))

    form = FrmAlunoUpdate(request.POST, instance=aluno)
    formset = TelefoneFormSet(request.POST, instance=aluno)

    if form.is_valid() and formset.is_valid():
        form.save()
        formset.save()

        return JsonResponse({
            'success': True,
            'mensagem': criarMensagemJson(
                'Aluno atualizado com sucesso!!!',
                'success'
            )
        })

    return JsonResponse({
        'success': False,
        'html': render_to_string(
            'aluno/aluno/partials/form_update.html',
            {
                'form': form,
                'formset': formset,
                'aluno': aluno
            },
            request=request
        )
    })
        
def pesquisar_aluno(request):
    nome = padronizar_nome(request.POST.get("nome", ""))
    filtro = request.POST.get("filtro")

    if len(nome) <= REF_TAMANHO_NOME:
        # Últimos 5 registros
        alunos = Aluno.retornarNUltimos().prefetch_related('telefones')
        nomes_duplicados = buscar_duplicados(alunos)
        html = renderizarTabela(alunos, nomes_duplicados, request)
        return JsonResponse({'html': html, 'mensagem': ''})  # sem mensagem

    alunos = pesquisar_alunos_por_nome(nome, filtro).prefetch_related('telefones')
    nomes_duplicados = buscar_duplicados(alunos)
    html = renderizarTabela(alunos, nomes_duplicados, request)

    if not alunos:
       
        return JsonResponse({'html': '', 'mensagem': criarMensagemJson('Aluno não Encontrado!','info')})
    
    return JsonResponse({'html': html, 'mensagem': ''})
        
def cancelarRM(request):
    rm = request.POST.get("rm")
    try:
        aluno = Aluno.objects.get(rm=rm)
    except Aluno.DoesNotExist:
        return JsonResponse({"success": False, "mensagem":criarMensagemJson('Aluno não Encontrado!', 'info')})

    # Defina explicitamente o status de cancelado
    aluno.status = Aluno.STATUS_CANCELADO
    aluno.save()

    return JsonResponse({"success": False, "mensagem":criarMensagemJson(f'Aluno {aluno.nome}, RM {aluno.rm} Cancelado com Sucesso!', 'success')})
 
def recarregarTabela(request):
    alunos = Aluno.retornarNUltimos().prefetch_related('telefones')
    nomes_duplicados = buscar_duplicados(alunos)
    html = renderizarTabela(alunos, nomes_duplicados, request)
  
    return JsonResponse({'html': html, 'mensagem': ''})  # sem mensagem

def buscar_dados_aluno(request):
    aluno = get_object_or_404(Aluno, rm=request.POST.get("rm"))

    form = FrmAlunoUpdate(instance=aluno)
    formset = TelefoneFormSet(instance=aluno)

    return render(
        request,
        "aluno/aluno/partials/form_update.html",
        {
            "form": form,
            "formset": formset,
            "aluno": aluno,
        }
    )

def buscarRMCancelar(request):
    rm = request.POST.get('rm')
    aluno = Aluno.objects.values('rm', 'nome').get(pk=rm)
    return JsonResponse({"rm": aluno['rm'], "nome": aluno['nome']})

   

aluno/views/ano.py
from django.shortcuts import HttpResponse, render

from aluno.utils.mensagem_http import criarMensagem

from aluno.models.ano import Ano
from aluno.services.ano import efetuar_lancamentos_fechamento_ano

# Create your views here.
def inicial_ano(request):
    return render(request,"aluno/ano/ano.html")

def gravar_ano(request):
    ano = Ano(ano=request.GET.get('ano'))
    try:
        ano.save()
        return criarMensagem("Ano salvo com sucesso","success")
    except Exception as err:
        return criarMensagem(f"Erro ao salvar ano ({err})!", "danger")

def excluir_ano(request):
    ano = Ano.objects.filter(pk=request.GET.get('ano'))[0]
    try:
        ano.delete()
        return criarMensagem("Ano deletado com sucesso", "success")
    except:
        return criarMensagem(f"Erro ao excluir ano ({ano})!","danger")

def buscar_ano(request):
    try:
        ano_recebido = request.GET.get("ano")
        if ano_recebido == "":
            ano_recebido = 0
        ano = Ano.objects.filter(ano=ano_recebido).filter()
        if ano:
             return render(request, 'aluno/ano/partials/listar_anos.html', {
                    'anos': ano,
             })
        else:
            return criarMensagem("Nenhum resultado!","info")

    except Exception as err:
        print(err)
        return criarMensagem("Algum erro aconteceu!","danger")
    
def listar_ano(request):
    anos = Ano.objects.all().order_by('-ano')[:10]
    return render(request, 'aluno/ano/partials/listar_anos.html', {
        'anos': anos,
    })

def fechar_abrir_ano(request):
    ano = Ano.objects.get(pk=request.GET.get('ano'))
    ano.fechado = not ano.fechado
    ano.save()
    efetuar_lancamentos_fechamento_ano(ano)

    return HttpResponse(ano.fechado)
    
def status_ano(request):
    ano = Ano.objects.get(pk=request.GET.get('ano'))
    return HttpResponse(ano.fechado)

def selecionar_ano(request):
    ano = Ano.objects.filter(ano=request.GET.get('ano')).first()
    return HttpResponse(ano.id)
   

aluno/templates/aluno/aluno/index.html
{% extends 'aluno/base.html' %}

{% block content %}
<style>
  input[type="checkbox"][name$="DELETE"] {
    display: none;
  }

  /* Linha marcada para remoção */
  .telefone-removido {
    opacity: 0.5;
    /* efeito visual de “desativado” */
    text-decoration: line-through;
    /* opcional */
  }
</style>
{% load static %}

<form id="cadastrarAluno" method="POST" action="{% url 'salvar_aluno' %}">
  {% csrf_token %}

  <div class="row">
    <div class="col-12">
      <h1 class="text-center">Registro de Alunos</h1>
    </div>
  </div>

  <div id="aluno" class="row mt-2 bg-body-secondary rounded-3">

    <!-- Nome do Aluno (já com ícone) -->
    <div class="col-sm-6 p-3">
      <div class="input-group">
        <span class="input-group-text bg-dark text-white">
          <i class="bi bi-search"></i>
        </span>
        {{ form.nome }}
      </div>
    </div>

    <!-- RA (agora com ícone) -->
    <div class="col-sm-2 p-3">
      <div class="input-group">
        <span class="input-group-text bg-dark text-white">
          <i class="bi bi-card-text"></i>
        </span>
        {{ form.ra }}
      </div>
    </div>

    <!-- Botão Gravar -->
    <div class="col-sm-2">
      <button type="submit" class="btn btn-outline-dark m-3" title="Registrar Aluno" id="gravarAluno">
        Gravar
      </button>
    </div>
    <div class="col-sm-2">
      <button type="button" class="btn btn-outline-primary m-3" title="Gerar Relatório" data-bs-toggle="modal"
        data-bs-target="#relatorioModal">
        Relatórios
      </button>
    </div>

  </div>
</form>


<div class="row mt-3">
  <div class="col-12 table-responsive">
    <table id="tabela" class="table table-hover table-bordered table-success">
      <thead>
        <th>RM</th>
        <th>Nome</th>
        <th class="text-center">RA</th>
        <th class="text-center">Turma</th>
        <th class="text-center">Telefone</th>
        <th class="text-center">Histórico</th>
        <th class="text-center">Declaração</th>
        <th class="text-center">Status</th>

        <!--<th class="text-center"> IA Matrícula</th>-->

      </thead>
      <tbody id="corpoTabela">

        <!-- Tabela dinâmica aparece aqui -->
      </tbody>
    </table>
  </div>
</div>


<!-- Modal Histórico de Matrículas-->
<div id="containerModalHistorico"></div>

<!-- Fim Modal Histórico de Matrículas-->

<!-- Modal Atualizar Registro-->
{% include 'aluno/aluno/partials/modal_atualizar.html' %}
<!-- Fim Modal Atualizar Registro-->

<!-- Modal Relatório -->
{% include 'aluno/aluno/partials/modal_relatorio.html' %}
<!-- Final Modal Relatório-->

<!-- Modal Resolução de Duplicidade-->
{% include 'aluno/aluno/partials/modal_duplicidade.html' %}
<!-- Fim Modal Resolução de Duplicidade-->


<script type="text/javascript">


  $("#cadastrarAluno").on("submit", function (e) {
    e.preventDefault();

    $.post({
      url: $(this).attr("action"),
      data: $(this).serialize(),
      success: function (response) {

        // Mensagem
        Alunos.notificar(response.mensagem)

        if (response.success && response.html) {
          $("#corpoTabela").html(response.html);
        }

        // Limpa formulário
        if (response.success) {
          $("#cadastrarAluno")[0].reset();
          $("#id_nome").focus();
        }

        setTimeout(() => {
          $("#mensagens").fadeOut();
        }, 3000);
      }
    });
  });

  $(document).on("submit", "#atualizarAluno", function (e) {
    e.preventDefault();

    $.post({
      url: $(this).attr("action"),
      data: $(this).serialize(),
      success: (response) => {
        if (response.success) {
          $(".modal").modal("hide");
          $("#mensagens")
            .stop(true, true)
            .html(response.mensagem)
            .show();
          $("#mensagens").html(response.mensagem);
          setTimeout(() => {
            $("#mensagens").fadeOut(1000, function () {
              $(this).html("").show(); // limpa e prepara para próxima mensagem
            });
          }, 3000);
          Alunos.recarregarTabela();
        } else {
          $("#dadosAluno").html(response.html);
        }
      }
    });
  });

</script>


{% endblock content %}

{% block script %}
<script src="{% static 'aluno/js/base.js' %}"></script>

<script src="{% static 'aluno/js/aluno.js' %}"></script>
<script src="{% static 'aluno/js/relatorio.js' %}"></script>
<script src="{% static 'aluno/js/classe.js' %}"></script>
<script src="{% static 'aluno/js/telefone.js' %}"></script>
<script src="{% static 'aluno/js/historico_matricula.js' %}"></script>


<script type="text/javascript">

  window.urls = window.urls || {};

  window.urls.historico_matricula = window.urls.historico_matricula || {
    buscar_historico_matricula: "{% url 'buscar_historico_matricula' %}"
  }


  window.urls.classe = window.urls.classe || {
    carregar_classe: "{% url 'carregarclasses' %}",
  };


  window.urls.aluno = window.urls.aluno || {
    buscar_aluno: "{% url 'buscarDadosAluno' %}",
    cancelar_rm: "{% url 'cancelarRM' %}",
    buscar_cancelar: "{% url 'buscarRMCancelar' %}",
    recarregar_tabela: "{% url 'recarregarTabela' %}",
    pesquisar_aluno: "{% url 'pesquisar_aluno' %}",
  };

  window.urls.relatorio = window.urls.relatorio || {
    relatorio_rm: "{% url 'baixarpdf' %}",
    relatorio_personalizavel: "{% url 'alunos_personalizada' %}",
    declaracao_matricula: "{% url 'baixar_declaracao_matricula' %}",
    lista_telefonica: "{% url 'listatelefonicapdf' %}"
  };

  Relatorios.init(window.urls.relatorio);
  Alunos.init(window.urls.aluno);
  Classes.init(window.urls.classe);
  Telefones.init();
  HistoricosMatriculas.init(window.urls.historico_matricula);


  const ano = Classes.getAno();
  if (ano) {
    Classes.carregarClasses(ano);
  }


</script>



{% endblock script %}